# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: VERSION
      run: |
        echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: SEMVER VERSION
      run: |
        SEMVER=( ${VERSION//./ } )
        echo "MAJOR=${SEMVER[0]}" >> $GITHUB_ENV
        echo "MINOR=${SEMVER[1]}" >> $GITHUB_ENV
        echo "PATCH=${SEMVER[2]}" >> $GITHUB_ENV
    - name: COMMIT_NUMBER
      run: |
        echo "COMMIT_NUMBER=${GITHUB_SHA::8}" >> $GITHUB_ENV
    - name: Get operator tag
      run: |
        echo "TAG=${VERSION}" >> $GITHUB_ENV
      if: env.PATCH != ''
    - name: Get operator commit
      run: |
        echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV
      if: env.VERSION == 'main'
    - name: Pull tercenctl
      run: docker pull tercen/tercenctl:release
    - name: Install operator
      run: |
        docker run -it --rm \
          -e TERCEN_USERNAME=${{ secrets.TERCEN_TEST_OPERATOR_USERNAME }} \
          -e TERCEN_USERNAME=${{ secrets.TERCEN_TEST_OPERATOR_PASSWORD }} \
          -e TERCEN_URI=${{ secrets.TERCEN_TEST_OPERATOR_URI }} \
          -e GITHUB_TOKEN=${GITHUB_TOKEN} \
          tercen/tercenctl:release operator install --tag ${TAG} --repo ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}